/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC17.app.src.main.java.cc17;

import CC17.app.src.main.java.cc17.BinaryTree;

public class App {


    public static void main(String[] args) {

        BinaryTree tree = new BinaryTree();
        tree.createBinaryTree();
        System.out.println(tree.breadthFirst((tree.getRoot())));
    }
}
