/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC16.app.src.test.java.cc16;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {

    }
}
