/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC14.app.src.main.java.cc14;

import CC14.app.src.main.java.cc14.QueueDuckGame;

public class App {
    public static void main(String[] args) {
        String [] circle = {"A","B","C","D","E"};
        int k=3;
        System.out.println(QueueDuckGame.DUCKDuckGoose(circle,k));
    }
}
