/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC14.app.src.test.java.cc14;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

}
