/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC34.app.src.main.java.cc34;


import java.util.ArrayList;
import java.util.HashMap;

public class App {

    public static void main(String[] args) {
        String text = "No. Try not. Do or do not. There is no try.";
        String text2="Taco cat ate a taco";
        String text3="In a galaxy far far away";
        System.out.println(FirstOccurrenceWord.firstRepeatedWord(text));
        System.out.println(FirstOccurrenceWord.firstRepeatedWord(text2));
        System.out.println(FirstOccurrenceWord.firstRepeatedWord(text3));
        System.out.println(firstRepeatedWord2(text));
        System.out.println(firstRepeatedWord2(text2));
        System.out.println(firstRepeatedWord2(text3));

    }
    public static String firstRepeatedWord2(String text) {
        HashMap<String, Integer> wordOccurrence = new HashMap<>();
        String mostCommonWord = "";
        int maxValue = 0;
        ArrayList<String> orderOfMostRepeatedWords = new ArrayList<>();
        String[] words = text.trim().toLowerCase().split("[^a-zA-Z0-9]+");
        for (String word : words) {
            wordOccurrence.computeIfPresent(word, (key,value)->value+1);
            wordOccurrence.putIfAbsent(word,1);
            if (wordOccurrence.get(word) > maxValue) {
                mostCommonWord = word;
                maxValue = wordOccurrence.get(word);
                orderOfMostRepeatedWords.add(word);
            }
            if (wordOccurrence.get(word) == maxValue && orderOfMostRepeatedWords.contains(word)) {
                mostCommonWord = word;
            }
        }
        return mostCommonWord;
    }
}
