/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC16.app.src.main.java.cc16;

public class App {

    public static void main(String[] args) {
        BinaryTree tree = new BinaryTree();
        tree.createBinaryTree();            //    3 <--1--> 2
        System.out.println(tree.treeMaxValue());


    }
}
