/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC30.lib.src.test.java.cc30;

import CC30.lib.src.main.java.cc30.HashMap;
import CC30.lib.src.main.java.cc30.Library;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    public void testSetMap(){
HashMap<Integer,String> students = new HashMap<>(5);
students.set(1,"saif");
        students.set(2,"ali");
        students.set(3,"mohammed");
        List<Integer> keys = new ArrayList<>();
        keys.add(1);
        keys.add(2);
        keys.add(3);
        Assertions.assertEquals(keys,students.keys());

    }
    @Test
    public void testGetMap(){
        HashMap<Integer,String> students = new HashMap<>(5);
        students.set(1,"saif");
        students.set(2,"ali");
        students.set(3,"mohammed");
        Assertions.assertTrue(students.get(2).equals("ali"));

    }
    @Test
    public void testCollisionMap(){
        HashMap<Integer,String> students = new HashMap<>(5);
        students.set(1,"saif");
        students.set(2,"ali");
        students.set(1,"mohammed");
        Assertions.assertTrue(students.get(1).equals("mohammed"));

    }
}
