/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC32.app.src.main.java.cc32;

import CC15.app.src.main.java.cc15.app.BinaryTree;

public class App {

    public static void main(String[] args) {
        BinaryTree tree1 = new BinaryTree();
        tree1.createBinaryTree();   //    3 <--1--> 2

        BinaryTree tree2 = new BinaryTree();   //    2 <--1--> 7
        BinaryTree.TreeNode root = new BinaryTree.TreeNode<>(5);
        tree2.setRoot(root);
        BinaryTree.TreeNode left = new BinaryTree.TreeNode<>(2);
        BinaryTree.TreeNode right = new BinaryTree.TreeNode<>(7);
        root.setLeft(left);
        root.setRight(right);
        System.out.println(TreeIntersection.treeIntersection(tree1,tree2));
    }
}
