/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC11.lib.src.test.java.cc11;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

}
