/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC18.app.src.main.java.cc18;


public class App {

    public static void main(String[] args) {
     TreeNode<Integer> root = new TreeNode<>(1);
        TreeNode<Integer> rootChild1 = new TreeNode<>(2);
        TreeNode<Integer> rootChild2 = new TreeNode<>(3);
        TreeNode<Integer> rootChild3 = new TreeNode<>(5);
        TreeNode<Integer> childOfRootChild2_1 = new TreeNode<>(6);
        TreeNode<Integer> childOfRootChild2_2 = new TreeNode<>(7);
        root.children.add(rootChild1);
        root.children.add(rootChild2);
        root.children.add(rootChild3);
        rootChild2.children.add(childOfRootChild2_1);
        rootChild2.children.add(childOfRootChild2_2);

        TreeNode.print(root);
        TreeNode.print(TreeNode.fizzBuzzTree(root));
    }
}
