/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC31.app.src.main.java.cc31;

import CC30.lib.src.main.java.cc30.HashMap;

public class App {

    public static void main(String[] args) {
        System.out.println(firstRepeatedWord("Once upon a time, there was a brave princess who..."));
        System.out.println(firstRepeatedWord("It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope,"));
        System.out.println(firstRepeatedWord("It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York..."));
    }
    public  static String firstRepeatedWord(String text){
        HashMap<String,Integer> wordOccurrence = new HashMap<>(10);
        String [] words = text.trim().toLowerCase().split("[^a-zA-Z0-9]+");
        for(String word: words){
            if(wordOccurrence.contains(word))
                return word;
            wordOccurrence.set(word,1);

        }
        return "no repeated words";
    }
}
