/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC15.app.src.main.java.cc15.app;


import CC15.app.src.main.java.cc15.app.BinaryTree.*;
import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        BinaryTree tree =new BinaryTree();
        tree.createBinaryTree();//    3 <--1--> 2
        System.out.println(tree.iterativePreOrderTraversal(tree.getRoot()));
        System.out.println();
        System.out.println(tree.iterativeInOrderTraversal(tree.getRoot()));
        System.out.println();
        System.out.println(tree.iterativePostOrderTraversal(tree.getRoot()));
    }
}
