/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC26.app.src.test.java.cc26;

import CC26.app.src.main.java.cc26.App;
import CC26.app.src.main.java.cc26.InsertionSort;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void testInsertionSort() {
        int sampleArray[] ={8,4,23,42,16,15};
        int expectedOutput[] ={4,8,15,16,23,42};
        Assertions.assertEquals(Arrays.toString(expectedOutput),Arrays.toString(InsertionSort.insertionSort(sampleArray)));
    }
}
