/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC27.app.src.test.java.cc27;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

}
