/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC30.lib.src.main.java.cc30;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
