/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC27.app.src.main.java.cc27;

import java.util.Arrays;

public class App {


    public static void main(String[] args) {
        int sampleArray[]={8,4,23,42,16,15};
        System.out.println("Array before sort: "+ Arrays.toString(sampleArray));
        MergeSort.mergeSort(sampleArray);
        System.out.println("Array after sort: "+ Arrays.toString(sampleArray));
    }
}
