/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC19.app.src.main.java.cc19;

import CC19.app.src.main.java.cc19.BinaryTree;

import static CC19.app.src.main.java.cc19.BinaryTree.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // Create your binary trees here
        BinaryTree.TreeNode tree1 = buildTree1();   // returns the root(directory) of a tree with 3 leafs (3 files)
        BinaryTree.TreeNode tree2 = buildTree2();   // returns the root(directory of a tree with 2 leafs (2 files)

        System.out.println( compareLeafNodes(tree1,tree2));
        System.out.println( compareLeafNodes(tree2,tree2));
        System.out.println( compareLeafNodes(tree1,tree1));


    }
}
