/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC33.app.src.test.java.cc33;

import CC30.lib.src.main.java.cc30.HashMap;
import CC33.app.src.main.java.cc33.LeftJoin;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

class AppTest {
    @Test
    void testLeftJoin1(){
        HashMap map1=new HashMap(5);
        map1.set("diligent","employed");
        map1.set("fond","enamored");
        map1.set("guide","usher");
        map1.set("outfit","garb");
        map1.set("wrath","anger");

        HashMap map2=new HashMap(5);
        map2.set("diligent","idle");
        map2.set("fond","averse");
        map2.set("guide","follow");
        map2.set("flow","jam");
        map2.set("wrath","delight");
        List<List<String>> result= LeftJoin.leftJoin(map1,map2);
        List<List<String>> expectedResult= List.of( List.of("diligent","employed", "idle"),List.of( "wrath", "anger", "delight"),
                    List.of("guide", "usher", "follow"),List.of("fond", "enamored", "averse"),List.of("outfit", "garb", null));
        Assertions.assertEquals(expectedResult,result);

    }
    @Test
    void testLeftJoin2(){
        HashMap map1=new HashMap(5);
        map1.set("beautiful","handsome");
        map1.set("smart","creative");
        map1.set("tall","long");

        HashMap map2=new HashMap(5);
        map2.set("beautiful","ugly");
        map2.set("smart","stupid");
        map2.set("tall","short");
        map2.set("hard","easy");
        List<List<String>> result= LeftJoin.leftJoin(map1,map2);
        List<List<String>> expectedResult= List.of( List.of( "smart","creative", "stupid"),List.of("beautiful","handsome", "ugly"),
                List.of("tall","long", "short"));
        Assertions.assertEquals(expectedResult,result);

    }
    @Test
    void testLeftJoin3(){
        HashMap map1=new HashMap(5);

        HashMap map2=new HashMap(5);
        map2.set("beautiful","ugly");
        map2.set("smart","stupid");
        map2.set("tall","short");
        map2.set("hard","easy");
        List<List<String>> result= LeftJoin.leftJoin(map1,map2);
        List<List<String>> expectedResult=new ArrayList<>();
        Assertions.assertEquals(expectedResult,result);

    }

}
