/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc41.app.src.main.java.cc41;

public class App {

    public static void main(String[] args) {
Navigator navigator = new Navigator();
navigator.addLocation("1");
        navigator.addLocation("2");
        navigator.addLocation("3");
        System.out.println( "Location History: " + navigator.getLocations().toString());
        System.out.println("previous location: "+ navigator.back());
        System.out.println("next location: "+ navigator.next());
    }
}
