/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc41.app.src.test.java.cc41;

import cc41.app.src.main.java.cc41.Navigator;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
@Test
    public void testNavigation(){
    Navigator navigator = new Navigator();
    navigator.addLocation("1");
    navigator.addLocation("2");
    navigator.addLocation("3");
    assertEquals("2",navigator.back());
    assertEquals("3",navigator.next());

}
}
