/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CC28.app.src.main.java.cc28;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;


public class App {
    public static void main(String[] args) {
        List<String> genres= new ArrayList<>();

        List<Movie> movieList= new ArrayList<>();
        movieList.add(new Movie("Interstaller",2018,genres));
        movieList.add(new Movie("Openhimer",2000,genres));
        movieList.add(new Movie("Batman",2019,genres));
        movieList.add(new Movie("HomeAlone",2020,genres));
        movieList.add(new Movie("HacksawRidge",2220,genres));
        movieList.add(new Movie("An hi",2220,genres));
        movieList.add(new Movie("Animal Shelter",2220,genres));
        System.out.println("before sort: "+movieList);
        Collections.sort(movieList);
        System.out.println("after sort by year: "+movieList);
    Collections.sort(movieList,new Movie.compareLexicographic());
        System.out.println("after sort by title: "+movieList);
    }
}
